import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { readdirSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { allTools, offerTools } from "../src/tools/index.js";
import type { SevdeskClient } from "../src/client.js";

// Fully mocked: these tests never call the sevDesk API.

type Route = { data?: any; error?: any };
/** A route is a fixed response or a function of the request init (peek and reserve share one path). */
type RouteSpec = Route | ((init: any) => Route);

function resolveRoute(spec: RouteSpec | undefined, init: any): Route | undefined {
  return typeof spec === "function" ? spec(init) : spec;
}

function mockClient(routes: { GET?: Record<string, RouteSpec>; POST?: Record<string, RouteSpec> }) {
  const GET = vi.fn(async (path: string, init?: any) => resolveRoute(routes.GET?.[path], init) ?? { error: { message: `unmocked GET ${path}` } });
  const POST = vi.fn(async (path: string, init?: any) => resolveRoute(routes.POST?.[path], init) ?? { error: { message: `unmocked POST ${path}` } });
  const PUT = vi.fn();
  const DELETE = vi.fn();
  return { client: { GET, POST, PUT, DELETE } as unknown as SevdeskClient, GET, POST, PUT, DELETE };
}

const NEXT_PATH = "/Order/Factory/getNextOrderNumber";
const ORDER_LIST_PATH = "/Order";
const SAVE_PATH = "/Order/Factory/saveOrder";
const saveResponse: Route = { data: { objects: { order: { id: 999, orderNumber: "AN-2026-1283", status: "100" }, orderPos: [{ id: 1 }] } } };

/** Next-number route: peek (`useNextNumber: "false"`) and reserve (`"true"`) responses. */
function nextNumberRoute(peek: Route, reserve: Route = peek): RouteSpec {
  return (init: any) => (init?.params?.query?.useNextNumber === "true" ? reserve : peek);
}

/** Order-list route: existing orders per orderNumber filter. */
function orderListRoute(byNumber: Record<string, any[]> = {}): RouteSpec {
  return (init: any) => ({ data: { objects: byNumber[init?.params?.query?.orderNumber] ?? [] } });
}

function isReserveCall(call: any[]): boolean {
  return call[0] === NEXT_PATH && call[1]?.params?.query?.useNextNumber === "true";
}

const validCreate = {
  contactId: 123,
  header: "Angebot DevOps Support",
  addressCountryId: 47,
  taxRule: "2" as const,
  taxText: "Steuerfrei - Ausfuhrlieferung",
  positions: [{ name: "Beratung", quantity: 2, price: 1500, unityId: 9, taxRate: 0 }],
};

function createRoutes(): { GET: Record<string, RouteSpec>; POST: Record<string, RouteSpec> } {
  return {
    GET: {
      [NEXT_PATH]: nextNumberRoute({ data: { objects: "AN-2026-1283" } }),
      [ORDER_LIST_PATH]: orderListRoute(),
    },
    POST: { [SAVE_PATH]: saveResponse },
  };
}

function draftOffer(overrides: Record<string, any> = {}) {
  return {
    id: "777",
    objectName: "Order",
    orderNumber: "AN-2026-1200",
    orderType: "AN",
    status: "100",
    taxRule: { id: "2", objectName: "TaxRule" },
    ...overrides,
  };
}

function updateRoutes(offer: Record<string, any>, positions: any[] = [{ id: "555", taxRate: "0", positionNumber: "0" }]) {
  return {
    GET: {
      "/Order/{orderId}": { data: { objects: [offer] } },
      "/Order/{orderId}/getPositions": { data: { objects: positions } },
    },
    POST: { [SAVE_PATH]: saveResponse },
  };
}

beforeEach(() => {
  vi.useFakeTimers({ toFake: ["Date"] });
  vi.setSystemTime(new Date("2026-10-07T10:00:00Z"));
  vi.stubEnv("SEVDESK_CONTACT_PERSON_ID", "");
});

afterEach(() => {
  vi.useRealTimers();
  vi.unstubAllEnvs();
});

const SRC_DIR = fileURLToPath(new URL("../src/", import.meta.url));
// src/generated holds the OpenAPI type declarations (gitignored, regenerated by `prepare`).
// It lists every endpoint as a type and makes no calls, so it is not scanned.
const SCAN_EXCLUDED_DIRS = new Set(["generated"]);

function sourceFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return SCAN_EXCLUDED_DIRS.has(entry.name) ? [] : sourceFiles(path);
    return /\.[cm]?[jt]s$/.test(entry.name) ? [path] : [];
  });
}

/** Order-domain endpoints that send, change status, convert or delete. Invoice send endpoints stay allowed. */
const FORBIDDEN_ORDER_CALLS: Array<[string, RegExp]> = [
  ["Order send/status endpoint", /\/Order\/[^"'`\s]*\/(sendViaEmail|sendBy|changeParameter|changeStatus)/],
  ["Order factory conversion", /create(Invoice|ContractNote|PackingList)FromOrder/],
  ["PUT or DELETE on an /Order path", /\b(PUT|DELETE)\b[^;]*?["'`]\/Order/],
];

function findForbiddenOrderCalls(source: string): string[] {
  return FORBIDDEN_ORDER_CALLS.filter(([, pattern]) => pattern.test(source)).map(([label]) => label);
}

describe("Offers: Draft-only-Garantie", () => {
  const forbiddenName = /send|status|delete|book|accept|reject/i;

  it("sollte genau die vier Angebots-Tools registrieren", () => {
    expect(Object.keys(offerTools).sort()).toEqual(["create_offer", "get_offer", "list_offers", "update_offer"]);
  });

  it("sollte kein Order-Tool mit send/status/delete/book/accept/reject registrieren", () => {
    const orderDomain = Object.keys(allTools).filter((n) => /offer|order|quote|angebot|auftrag/i.test(n));
    expect(orderDomain.sort()).toEqual(["create_offer", "get_offer", "list_offers", "update_offer"]);
    for (const name of orderDomain) {
      expect(name).not.toMatch(forbiddenName);
    }
  });

  it("sollte in keiner Datei unter src/ Order-Sende-, Status-, Konvertierungs- oder Lösch-Endpunkte aufrufen", () => {
    const files = sourceFiles(SRC_DIR);
    expect(files.map((f) => relative(SRC_DIR, f))).toContain(join("tools", "offers.ts"));
    expect(files.map((f) => relative(SRC_DIR, f))).toContain(join("tools", "invoices.ts"));
    const hits = files.flatMap((file) =>
      findForbiddenOrderCalls(readFileSync(file, "utf8")).map((label) => `${relative(SRC_DIR, file)}: ${label}`)
    );
    expect(hits).toEqual([]);
  });

  it.each([
    ['client.POST("/Order/{orderId}/sendViaEmail", {})', "Order send/status endpoint"],
    ['client.PUT("/Order/{orderId}/sendBy", {})', "Order send/status endpoint"],
    ['client.PUT("/Order/{orderId}/changeParameter", {})', "Order send/status endpoint"],
    ['client.POST("/Invoice/Factory/createInvoiceFromOrder", {})', "Order factory conversion"],
    ['client.POST("/Order/Factory/createContractNoteFromOrder", {})', "Order factory conversion"],
    ['client.POST("/Order/Factory/createPackingListFromOrder", {})', "Order factory conversion"],
    ['client.DELETE("/Order/{orderId}", {})', "PUT or DELETE on an /Order path"],
    ['(client.PUT as any)(\n  "/Order/{orderId}", {})', "PUT or DELETE on an /Order path"],
    ['client.DELETE("/OrderPos/{orderPosId}", {})', "PUT or DELETE on an /Order path"],
  ])("sollte den Scan für %s auslösen", (snippet, label) => {
    expect(findForbiddenOrderCalls(snippet)).toContain(label);
  });

  it("sollte Rechnungsversand und lesende Order-Aufrufe nicht melden", () => {
    expect(findForbiddenOrderCalls('client.POST("/Invoice/{invoiceId}/sendViaEmail", {});')).toEqual([]);
    expect(findForbiddenOrderCalls('client.PUT("/Invoice/{invoiceId}/sendBy", {});')).toEqual([]);
    expect(findForbiddenOrderCalls('client.GET("/Order/{orderId}", {}); client.POST("/Order/Factory/saveOrder", {});')).toEqual([]);
  });

  it("sollte in offers.ts weder PUT noch DELETE noch Sende- oder Konvertierungs-Tokens verwenden", () => {
    const source = readFileSync(new URL("../src/tools/offers.ts", import.meta.url), "utf8");
    for (const token of [
      "sendViaEmail",
      "sendBy",
      "changeParameter",
      "changeStatus",
      "createInvoiceFromOrder",
      "createContractNoteFromOrder",
      "client.PUT",
      "client.DELETE",
    ]) {
      expect(source).not.toContain(token);
    }
  });
});

describe("create_offer", () => {
  it("sollte einen Entwurf mit reservierter Angebotsnummer anlegen (Peek, Prüfung, Reservierung, Speichern)", async () => {
    const { client, GET, POST, PUT, DELETE } = mockClient(createRoutes());
    const result = await offerTools.create_offer.handler(client, validCreate);

    // Exact call order: peek -> duplicate guard -> reserve -> saveOrder.
    expect(GET).toHaveBeenCalledTimes(3);
    expect(GET.mock.calls[0]).toEqual([NEXT_PATH, { params: { query: { orderType: "AN", useNextNumber: "false" } } }]);
    expect(GET.mock.calls[1][0]).toBe(ORDER_LIST_PATH);
    const guardQuery = GET.mock.calls[1][1].params.query;
    expect(guardQuery).toEqual({ orderNumber: "AN-2026-1283", limit: 100 });
    for (const key of ["orderType", "status", "contact[id]", "contact[objectName]"]) {
      expect(guardQuery).not.toHaveProperty(key);
    }
    expect(GET.mock.calls[2]).toEqual([NEXT_PATH, { params: { query: { orderType: "AN", useNextNumber: "true" } } }]);
    expect(POST).toHaveBeenCalledTimes(1);
    const lastGetOrder = Math.max(...GET.mock.invocationCallOrder);
    expect(POST.mock.invocationCallOrder[0]).toBeGreaterThan(lastGetOrder);
    expect(GET.mock.invocationCallOrder[0]).toBeLessThan(GET.mock.invocationCallOrder[1]);
    expect(GET.mock.invocationCallOrder[1]).toBeLessThan(GET.mock.invocationCallOrder[2]);

    const [path, init] = POST.mock.calls[0];
    expect(path).toBe(SAVE_PATH);
    const { order, orderPosSave, orderPosDelete } = init.body;

    expect(order.id).toBeNull();
    expect(order.orderNumber).toBe("AN-2026-1283");
    expect(order.status).toBe(100);
    expect(order.orderType).toBe("AN");
    expect(order.mapAll).toBe(true);
    expect(order.taxRule).toEqual({ id: "2", objectName: "TaxRule" });
    expect(order.taxText).toBe("Steuerfrei - Ausfuhrlieferung");
    expect(order.taxRate).toBe(0);
    expect(order.contact).toEqual({ id: 123, objectName: "Contact" });
    expect(order.contactPerson).toEqual({ id: 389230, objectName: "SevUser" });
    expect(order.addressCountry).toEqual({ id: 47, objectName: "StaticCountry" });
    expect(order.orderDate).toBe("07.10.2026");
    expect(order.currency).toBe("EUR");
    expect(order).not.toHaveProperty("address");
    expect(orderPosDelete).toBeNull();

    expect(orderPosSave).toHaveLength(1);
    orderPosSave.forEach((pos: any, i: number) => {
      expect(pos.objectName).toBe("OrderPos");
      expect(pos.mapAll).toBe(true);
      expect(pos.unity).toEqual({ id: 9, objectName: "Unity" });
      expect(pos.taxRate).toBe(0);
      expect(pos.positionNumber).toBe(i);
      expect(pos.price).toBe("1500");
      expect(pos.part).toBeNull();
      expect(pos).not.toHaveProperty("id");
    });

    expect(result.note).toContain("status 100");
    expect(result.offer).toEqual(saveResponse.data.objects.order);
    expect(PUT).not.toHaveBeenCalled();
    expect(DELETE).not.toHaveBeenCalled();
  });

  it("sollte status, orderNumber und orderType aus der Eingabe ignorieren", async () => {
    const { client, POST } = mockClient(createRoutes());
    await offerTools.create_offer.handler(client, {
      ...validCreate,
      status: 200,
      orderNumber: "AN-1999-1",
      orderType: "AB",
    } as any);
    const { order } = POST.mock.calls[0][1].body;
    expect(order.status).toBe(100);
    expect(order.orderNumber).toBe("AN-2026-1283");
    expect(order.orderType).toBe("AN");
  });

  describe("Angebotsnummer und Duplikatschutz", () => {
    it("sollte eine bereits vergebene Nummer ablehnen und nichts anlegen", async () => {
      const routes = createRoutes();
      routes.GET[NEXT_PATH] = nextNumberRoute({ data: { objects: "AN-2026-1281" } });
      routes.GET[ORDER_LIST_PATH] = orderListRoute({
        "AN-2026-1281": [
          { id: "30234435", orderNumber: "AN-2026-1281", status: "500", contact: { id: "137644298" } },
          { id: "28275368", orderNumber: "AN-2026-1281", status: "100", contact: { id: "131897733" } },
        ],
      });
      const { client, GET, POST, PUT, DELETE } = mockClient(routes);
      const error: Error = await offerTools.create_offer.handler(client, validCreate).then(
        () => {
          throw new Error("expected create_offer to reject");
        },
        (e: Error) => e
      );
      expect(error.message).toContain("AN-2026-1281");
      expect(error.message).toContain("30234435");
      expect(error.message).toContain("28275368");
      expect(error.message).toContain("No offer was created");
      expect(error.message).not.toContain("already moved past");
      expect(GET.mock.calls.some(isReserveCall)).toBe(false);
      expect(POST).not.toHaveBeenCalled();
      expect(PUT).not.toHaveBeenCalled();
      expect(DELETE).not.toHaveBeenCalled();
    });

    it("sollte eine freie Nummer anlegen, auch wenn dieselbe Laufnummer in einem anderen Jahr existiert", async () => {
      const routes = createRoutes();
      routes.GET[NEXT_PATH] = nextNumberRoute({ data: { objects: "AN-2026-1281" } });
      routes.GET[ORDER_LIST_PATH] = () => ({ data: { objects: [{ id: "21173457", orderNumber: "AN-2025-1281", status: "500" }] } });
      const { client, POST } = mockClient(routes);
      await offerTools.create_offer.handler(client, validCreate);
      expect(POST).toHaveBeenCalledTimes(1);
      expect(POST.mock.calls[0][1].body.order.orderNumber).toBe("AN-2026-1281");
      expect(POST.mock.calls[0][1].body.order.status).toBe(100);
    });

    it("sollte eine abweichende reservierte Nummer erneut prüfen und speichern", async () => {
      const routes = createRoutes();
      routes.GET[NEXT_PATH] = nextNumberRoute({ data: { objects: "AN-2026-1283" } }, { data: { objects: "AN-2026-1284" } });
      const { client, GET, POST } = mockClient(routes);
      await offerTools.create_offer.handler(client, validCreate);
      expect(GET).toHaveBeenCalledTimes(4);
      expect(GET.mock.calls[3][0]).toBe(ORDER_LIST_PATH);
      expect(GET.mock.calls[3][1].params.query).toEqual({ orderNumber: "AN-2026-1284", limit: 100 });
      expect(POST.mock.invocationCallOrder[0]).toBeGreaterThan(GET.mock.invocationCallOrder[3]);
      expect(POST.mock.calls[0][1].body.order.orderNumber).toBe("AN-2026-1284");
    });

    it("sollte eine abweichende reservierte Nummer ablehnen, wenn sie bereits vergeben ist", async () => {
      const routes = createRoutes();
      routes.GET[NEXT_PATH] = nextNumberRoute({ data: { objects: "AN-2026-1283" } }, { data: { objects: "AN-2026-1284" } });
      routes.GET[ORDER_LIST_PATH] = orderListRoute({
        "AN-2026-1284": [{ id: "40000001", orderNumber: "AN-2026-1284", status: "200", contact: { id: "1" } }],
      });
      const { client, POST, PUT, DELETE } = mockClient(routes);
      const error: Error = await offerTools.create_offer.handler(client, validCreate).then(
        () => {
          throw new Error("expected create_offer to reject");
        },
        (e: Error) => e
      );
      expect(error.message).toContain("AN-2026-1284");
      expect(error.message).toContain("40000001");
      expect(error.message).toContain("already moved past");
      expect(POST).not.toHaveBeenCalled();
      expect(PUT).not.toHaveBeenCalled();
      expect(DELETE).not.toHaveBeenCalled();
    });

    it("sollte bei einem Fehler beim Lesen der nächsten Nummer abbrechen, ohne zu speichern", async () => {
      const routes = createRoutes();
      routes.GET[NEXT_PATH] = nextNumberRoute({ error: { message: "boom" } });
      const { client, GET, POST } = mockClient(routes);
      await expect(offerTools.create_offer.handler(client, validCreate)).rejects.toThrow("boom");
      expect(GET.mock.calls.some(isReserveCall)).toBe(false);
      expect(POST).not.toHaveBeenCalled();
    });

    it("sollte bei einem Fehler der Duplikatprüfung abbrechen, ohne zu reservieren oder zu speichern", async () => {
      const routes = createRoutes();
      routes.GET[ORDER_LIST_PATH] = { error: { message: "list failed" } };
      const { client, GET, POST } = mockClient(routes);
      await expect(offerTools.create_offer.handler(client, validCreate)).rejects.toThrow("list failed");
      expect(GET.mock.calls.some(isReserveCall)).toBe(false);
      expect(POST).not.toHaveBeenCalled();
    });

    it("sollte bei einem Fehler beim Reservieren abbrechen, ohne zu speichern", async () => {
      const routes = createRoutes();
      routes.GET[NEXT_PATH] = nextNumberRoute({ data: { objects: "AN-2026-1283" } }, { error: { message: "reserve failed" } });
      const { client, POST } = mockClient(routes);
      await expect(offerTools.create_offer.handler(client, validCreate)).rejects.toThrow("reserve failed");
      expect(POST).not.toHaveBeenCalled();
    });

    it.each([
      ["fehlendes objects", {}, /did not return/],
      ["leerer String", { objects: "" }, /did not return/],
      ["Zahl statt String", { objects: 1283 }, /did not return/],
      ["unaufgelöster Platzhalter", { objects: "AN-%YYYY-1" }, /Unsupported offer number/],
    ])("sollte bei %s abbrechen, statt eine Nummer zu erfinden", async (_label, data, message) => {
      const routes = createRoutes();
      routes.GET[NEXT_PATH] = nextNumberRoute({ data });
      const { client, GET, POST } = mockClient(routes);
      await expect(offerTools.create_offer.handler(client, validCreate)).rejects.toThrow(message);
      expect(GET.mock.calls.some(isReserveCall)).toBe(false);
      expect(POST).not.toHaveBeenCalled();
    });

    it("sollte eine ungültige reservierte Nummer ablehnen, ohne zu speichern", async () => {
      const routes = createRoutes();
      routes.GET[NEXT_PATH] = nextNumberRoute({ data: { objects: "AN-2026-1283" } }, { data: { objects: "" } });
      const { client, POST } = mockClient(routes);
      await expect(offerTools.create_offer.handler(client, validCreate)).rejects.toThrow(/did not return/);
      expect(POST).not.toHaveBeenCalled();
    });

    it("sollte höchstens einmal pro Aufruf reservieren", async () => {
      const { client, GET } = mockClient(createRoutes());
      await offerTools.create_offer.handler(client, validCreate);
      expect(GET.mock.calls.filter(isReserveCall)).toHaveLength(1);
    });
  });

  it("sollte Inlandsangebote mit 19 % und 7 % akzeptieren", async () => {
    const { client, POST } = mockClient(createRoutes());
    await offerTools.create_offer.handler(client, {
      ...validCreate,
      taxRule: "1",
      taxText: "Umsatzsteuer",
      address: "Kunde GmbH\nStraße 1\n50667 Köln",
      positions: [
        { name: "Beratung", quantity: 1, price: 1000, unityId: 9, taxRate: 19 },
        { name: "Buch", quantity: 1, price: 20, unityId: 1, taxRate: 7, partId: 42 },
      ],
    });
    const { order, orderPosSave } = POST.mock.calls[0][1].body;
    expect(order.taxRate).toBe(19);
    expect(order.taxRule).toEqual({ id: "1", objectName: "TaxRule" });
    expect(order.address).toBe("Kunde GmbH\nStraße 1\n50667 Köln");
    expect(orderPosSave.map((p: any) => p.taxRate)).toEqual([19, 7]);
    expect(orderPosSave[1].part).toEqual({ id: 42, objectName: "Part" });
    expect(orderPosSave[1].positionNumber).toBe(1);
  });

  it("sollte orderDate und Währung übernehmen", async () => {
    const { client, POST } = mockClient(createRoutes());
    await offerTools.create_offer.handler(client, { ...validCreate, orderDate: "2026-11-02", currency: "USD" });
    const { order } = POST.mock.calls[0][1].body;
    expect(order.orderDate).toBe("02.11.2026");
    expect(order.currency).toBe("USD");
  });

  it("sollte contactPersonId aus Eingabe oder Umgebung verwenden", async () => {
    const first = mockClient(createRoutes());
    await offerTools.create_offer.handler(first.client, { ...validCreate, contactPersonId: 42 });
    expect(first.POST.mock.calls[0][1].body.order.contactPerson).toEqual({ id: 42, objectName: "SevUser" });

    vi.stubEnv("SEVDESK_CONTACT_PERSON_ID", "4711");
    const second = mockClient(createRoutes());
    await offerTools.create_offer.handler(second.client, validCreate);
    expect(second.POST.mock.calls[0][1].body.order.contactPerson.id).toBe(4711);
  });

  it("sollte eine unzulässige taxRule/taxRate-Kombination vor jedem API-Aufruf ablehnen", async () => {
    const { client, GET, POST } = mockClient(createRoutes());
    await expect(
      offerTools.create_offer.handler(client, {
        ...validCreate,
        positions: [{ name: "Beratung", quantity: 1, price: 100, unityId: 9, taxRate: 19 }],
      })
    ).rejects.toThrow(/19/);
    expect(GET).not.toHaveBeenCalled();
    expect(POST).not.toHaveBeenCalled();
  });

  it("sollte Positionen ohne unityId und leere Positionslisten auch bei direktem Aufruf ablehnen", async () => {
    const { client, GET, POST } = mockClient(createRoutes());
    await expect(
      offerTools.create_offer.handler(client, {
        ...validCreate,
        positions: [{ name: "Beratung", quantity: 1, price: 100, taxRate: 0 }],
      } as any)
    ).rejects.toThrow(/unityId/);
    await expect(offerTools.create_offer.handler(client, { ...validCreate, positions: [] })).rejects.toThrow(/position/);
    expect(GET).not.toHaveBeenCalled();
    expect(POST).not.toHaveBeenCalled();
  });

  describe("Eingabevalidierung", () => {
    const schema = offerTools.create_offer.inputSchema;
    const position = validCreate.positions[0];

    it("sollte gültige Eingaben akzeptieren", () => {
      expect(schema.safeParse(validCreate).success).toBe(true);
    });

    it.each([
      ["fehlende unityId", { positions: [{ name: "x", quantity: 1, price: 1, taxRate: 0 }] }],
      ["leere Positionsliste", { positions: [] }],
      ["Menge 0", { positions: [{ ...position, quantity: 0 }] }],
      ["taxRule 8", { taxRule: "8" }],
      ["zusätzliches status", { status: 100 }],
      ["zusätzliche orderNumber", { orderNumber: "AN-2026-1" }],
      ["zusätzlicher orderType", { orderType: "AB" }],
      ["fehlender taxText", { taxText: undefined }],
      ["deutsches Datumsformat", { orderDate: "07.10.2026" }],
    ])("sollte %s ablehnen", (_label, override) => {
      expect(schema.safeParse({ ...validCreate, ...override }).success).toBe(false);
    });

    it("sollte limit > 100 bei list_offers ablehnen", () => {
      expect(offerTools.list_offers.inputSchema.safeParse({ limit: 101 }).success).toBe(false);
    });

    it("sollte status bei update_offer ablehnen", () => {
      expect(offerTools.update_offer.inputSchema.safeParse({ orderId: 1, status: 200 }).success).toBe(false);
      expect(offerTools.update_offer.inputSchema.safeParse({ orderId: 1, orderNumber: "AN-1" }).success).toBe(false);
      expect(offerTools.update_offer.inputSchema.safeParse({ orderId: 1, headText: "x" }).success).toBe(true);
    });
  });
});

describe("list_offers", () => {
  it("sollte nur Angebote mit Filtern abfragen und zurückgeben", async () => {
    const { client, GET } = mockClient({
      GET: {
        "/Order": {
          data: {
            objects: [
              { id: "1", orderNumber: "AN-2026-1", orderType: "AN", status: "100", header: "A", sumNet: "100", orderDate: "2026-10-01", contact: { id: "123", objectName: "Contact" } },
              { id: "2", orderNumber: "AB-2026-1", orderType: "AB", status: "100", header: "B", sumNet: "50" },
            ],
          },
        },
      },
    });
    const result = await offerTools.list_offers.handler(client, { contactId: 123, status: "100" });

    const [path, init] = GET.mock.calls[0];
    expect(path).toBe("/Order");
    expect(init.params.query).toMatchObject({
      orderType: "AN",
      limit: 20,
      status: 100,
      "contact[id]": 123,
      "contact[objectName]": "Contact",
    });
    expect(result.offers).toHaveLength(1);
    expect(result.offers[0]).toMatchObject({
      id: "1",
      orderNumber: "AN-2026-1",
      status: "100",
      sumNet: "100",
      header: "A",
      contact: { id: "123", objectName: "Contact" },
    });
  });

  it("sollte ohne contactId keinen Kontaktfilter senden", async () => {
    const { client, GET } = mockClient({ GET: { "/Order": { data: { objects: [] } } } });
    await offerTools.list_offers.handler(client, { limit: 5, offset: 10 });
    const query = GET.mock.calls[0][1].params.query;
    expect(query).toMatchObject({ orderType: "AN", limit: 5, offset: 10 });
    expect(query["contact[id]"]).toBeUndefined();
    expect(query["contact[objectName]"]).toBeUndefined();
  });
});

describe("get_offer", () => {
  it("sollte Angebot und Positionen zurückgeben", async () => {
    const offer = draftOffer();
    const positions = [{ id: "555", name: "Beratung" }];
    const { client, GET, POST } = mockClient(updateRoutes(offer, positions));
    const result = await offerTools.get_offer.handler(client, { orderId: 777 });
    expect(result).toEqual({ offer, positions });
    expect(GET.mock.calls[0][1].params.path.orderId).toBe(777);
    expect(GET.mock.calls[1][0]).toBe("/Order/{orderId}/getPositions");
    expect(POST).not.toHaveBeenCalled();
  });

  it("sollte Aufträge ablehnen, die keine Angebote sind", async () => {
    const { client, GET } = mockClient(updateRoutes(draftOffer({ orderType: "AB" })));
    await expect(offerTools.get_offer.handler(client, { orderId: 777 })).rejects.toThrow(/not an offer/);
    expect(GET).toHaveBeenCalledTimes(1);
  });

  it("sollte ablehnen, wenn das Angebot nicht existiert", async () => {
    const { client } = mockClient({ GET: { "/Order/{orderId}": { data: { objects: [] } } } });
    await expect(offerTools.get_offer.handler(client, { orderId: 1 })).rejects.toThrow(/not found/);
  });
});

describe("update_offer", () => {
  it.each(["200", "300", "500", "1000"])("sollte ein Angebot mit Status %s ablehnen", async (status) => {
    const { client, POST, PUT, DELETE } = mockClient(updateRoutes(draftOffer({ status })));
    await expect(offerTools.update_offer.handler(client, { orderId: 777, headText: "neu" })).rejects.toThrow(/only draft/);
    expect(POST).not.toHaveBeenCalled();
    expect(PUT).not.toHaveBeenCalled();
    expect(DELETE).not.toHaveBeenCalled();
  });

  it("sollte Aufträge ablehnen, die keine Angebote sind", async () => {
    const { client, POST } = mockClient(updateRoutes(draftOffer({ orderType: "AB" })));
    await expect(offerTools.update_offer.handler(client, { orderId: 777, headText: "neu" })).rejects.toThrow(/not an offer/);
    expect(POST).not.toHaveBeenCalled();
  });

  it("sollte Kopfdaten eines Entwurfs ändern und Status 100 beibehalten", async () => {
    const { client, GET, POST, PUT, DELETE } = mockClient(updateRoutes(draftOffer()));
    const result = await offerTools.update_offer.handler(client, { orderId: 777, headText: "neu", orderDate: "2026-10-09" });
    const [path, init] = POST.mock.calls[0];
    expect(path).toBe(SAVE_PATH);
    const { order, orderPosSave, orderPosDelete } = init.body;
    expect(order).toMatchObject({
      id: 777,
      objectName: "Order",
      mapAll: true,
      status: 100,
      orderType: "AN",
      orderNumber: "AN-2026-1200",
      headText: "neu",
      orderDate: "09.10.2026",
    });
    expect(order).not.toHaveProperty("header");
    expect(order).not.toHaveProperty("taxRule");
    expect(orderPosSave).toEqual([]);
    expect(orderPosDelete).toBeNull();
    expect(result.note).toContain("status 100");
    // update_offer keeps the stored number and never reads or reserves a new one.
    expect(GET.mock.calls.some((call) => call[0] === NEXT_PATH)).toBe(false);
    expect(PUT).not.toHaveBeenCalled();
    expect(DELETE).not.toHaveBeenCalled();
  });

  it("sollte status, orderNumber und orderType aus der Eingabe ignorieren", async () => {
    const { client, POST } = mockClient(updateRoutes(draftOffer()));
    await offerTools.update_offer.handler(client, {
      orderId: 777,
      headText: "neu",
      status: 500,
      orderNumber: "AN-1999-1",
      orderType: "AB",
    } as any);
    const { order } = POST.mock.calls[0][1].body;
    expect(order.status).toBe(100);
    expect(order.orderNumber).toBe("AN-2026-1200");
    expect(order.orderType).toBe("AN");
  });

  it("sollte bestehende Positionen ändern und neue hinzufügen", async () => {
    const { client, POST } = mockClient(updateRoutes(draftOffer()));
    await offerTools.update_offer.handler(client, {
      orderId: 777,
      positions: [
        { id: 555, name: "Beratung", quantity: 3, price: 1200, unityId: 9, taxRate: 0 },
        { name: "Workshop", quantity: 1, price: 2000, unityId: 13, taxRate: 0, positionNumber: 5 },
      ],
    });
    const { orderPosSave, orderPosDelete } = POST.mock.calls[0][1].body;
    expect(orderPosSave[0]).toMatchObject({ id: 555, mapAll: true, unity: { id: 9, objectName: "Unity" }, taxRate: 0, positionNumber: 0 });
    expect(orderPosSave[1]).not.toHaveProperty("id");
    expect(orderPosSave[1]).toMatchObject({ mapAll: true, unity: { id: 13, objectName: "Unity" }, positionNumber: 5 });
    expect(orderPosDelete).toBeNull();
  });

  describe("positionNumber", () => {
    const threePositions = [
      { id: "551", name: "Analyse", taxRate: "0", positionNumber: "0" },
      { id: "552", name: "Umsetzung", taxRate: "0", positionNumber: "1" },
      { id: "553", name: "Betrieb", taxRate: "0", positionNumber: "2" },
    ];

    it("sollte neue Positionen nach der höchsten bestehenden Nummer anhängen", async () => {
      const { client, POST } = mockClient(updateRoutes(draftOffer(), threePositions));
      await offerTools.update_offer.handler(client, {
        orderId: 777,
        positions: [
          { name: "Workshop", quantity: 1, price: 2000, unityId: 13, taxRate: 0 },
          { name: "Reise", quantity: 1, price: 300, unityId: 7, taxRate: 0 },
        ],
      });
      const { orderPosSave } = POST.mock.calls[0][1].body;
      expect(orderPosSave.map((p: any) => p.positionNumber)).toEqual([3, 4]);
      orderPosSave.forEach((p: any) => expect(p).not.toHaveProperty("id"));
    });

    it("sollte die Nummer einer geänderten bestehenden Position beibehalten", async () => {
      const { client, POST } = mockClient(updateRoutes(draftOffer(), threePositions));
      await offerTools.update_offer.handler(client, {
        orderId: 777,
        positions: [{ id: 553, name: "Betrieb", quantity: 12, price: 900, unityId: 9, taxRate: 0 }],
      });
      const { orderPosSave } = POST.mock.calls[0][1].body;
      expect(orderPosSave).toHaveLength(1);
      expect(orderPosSave[0]).toMatchObject({ id: 553, positionNumber: 2, quantity: 12 });
    });

    it("sollte eine explizite positionNumber übernehmen und neue Positionen danach nummerieren", async () => {
      const { client, POST } = mockClient(updateRoutes(draftOffer(), threePositions));
      await offerTools.update_offer.handler(client, {
        orderId: 777,
        positions: [
          { id: 551, name: "Analyse", quantity: 1, price: 500, unityId: 9, taxRate: 0, positionNumber: 7 },
          { name: "Workshop", quantity: 1, price: 2000, unityId: 13, taxRate: 0 },
        ],
      });
      const { orderPosSave } = POST.mock.calls[0][1].body;
      expect(orderPosSave.map((p: any) => p.positionNumber)).toEqual([7, 8]);
    });
  });

  it("sollte eine neue taxRule zusammen mit allen neu eingereichten Positionen speichern", async () => {
    const existing = [
      { id: "551", name: "Beratung", taxRate: "19", positionNumber: "0" },
      { id: "552", name: "Workshop", taxRate: "19", positionNumber: "1" },
    ];
    const { client, POST } = mockClient(updateRoutes(draftOffer({ taxRule: { id: "1" } }), existing));
    await offerTools.update_offer.handler(client, {
      orderId: 777,
      taxRule: "2",
      taxText: "Steuerfrei - Ausfuhrlieferung",
      positions: [
        { id: 551, name: "Beratung", quantity: 2, price: 1500, unityId: 9, taxRate: 0 },
        { id: 552, name: "Workshop", quantity: 1, price: 2000, unityId: 13, taxRate: 0 },
        { name: "Reise", quantity: 1, price: 300, unityId: 7, taxRate: 0 },
      ],
    });
    expect(POST).toHaveBeenCalledTimes(1);
    const { order, orderPosSave } = POST.mock.calls[0][1].body;
    expect(order.taxRule).toEqual({ id: "2", objectName: "TaxRule" });
    expect(order.taxText).toBe("Steuerfrei - Ausfuhrlieferung");
    expect(orderPosSave.map((p: any) => p.taxRate)).toEqual([0, 0, 0]);
    expect(orderPosSave.map((p: any) => p.positionNumber)).toEqual([0, 1, 2]);
  });

  it("sollte eine neue taxRule ablehnen, wenn nicht eingereichte Positionen nicht passen", async () => {
    const existing = [
      { id: "551", name: "Beratung", taxRate: "19", positionNumber: "0" },
      { id: "552", name: "Workshop", taxRate: "19", positionNumber: "1" },
    ];
    const { client, POST, PUT, DELETE } = mockClient(updateRoutes(draftOffer({ taxRule: { id: "1" } }), existing));
    const error: Error = await offerTools.update_offer
      .handler(client, {
        orderId: 777,
        taxRule: "2",
        positions: [
          { id: 552, name: "Workshop", quantity: 1, price: 2000, unityId: 13, taxRate: 0 },
          { name: "Reise", quantity: 1, price: 300, unityId: 7, taxRate: 0 },
        ],
      })
      .then(
        () => {
          throw new Error("expected update_offer to reject");
        },
        (e: Error) => e
      );
    expect(error.message).toMatch(/Cannot change taxRule to 2: existing position\(s\) id 551 'Beratung' \(taxRate 19\)/);
    expect(error.message).toMatch(/Resubmit those positions/);
    expect(error.message).not.toMatch(/id 552/);
    expect(POST).not.toHaveBeenCalled();
    expect(PUT).not.toHaveBeenCalled();
    expect(DELETE).not.toHaveBeenCalled();
  });

  it("sollte fremde Positions-IDs ablehnen", async () => {
    const { client, POST } = mockClient(updateRoutes(draftOffer()));
    await expect(
      offerTools.update_offer.handler(client, {
        orderId: 777,
        positions: [{ id: 999, name: "x", quantity: 1, price: 1, unityId: 9, taxRate: 0 }],
      })
    ).rejects.toThrow(/999/);
    expect(POST).not.toHaveBeenCalled();
  });

  it("sollte Steuersätze gegen die taxRule des Angebots prüfen", async () => {
    const { client, POST } = mockClient(updateRoutes(draftOffer()));
    await expect(
      offerTools.update_offer.handler(client, {
        orderId: 777,
        positions: [{ name: "x", quantity: 1, price: 1, unityId: 9, taxRate: 19 }],
      })
    ).rejects.toThrow(/taxRule 2/);
    expect(POST).not.toHaveBeenCalled();
  });

  it("sollte eine neue taxRule gegen die bestehenden Positionen prüfen", async () => {
    const { client, POST } = mockClient(updateRoutes(draftOffer({ taxRule: { id: "1" } }), [{ id: "555", taxRate: "19" }]));
    await expect(offerTools.update_offer.handler(client, { orderId: 777, taxRule: "2" })).rejects.toThrow(/19/);
    expect(POST).not.toHaveBeenCalled();
  });

  it("sollte ohne Änderungen ablehnen", async () => {
    const { client, GET, POST } = mockClient(updateRoutes(draftOffer()));
    await expect(offerTools.update_offer.handler(client, { orderId: 777 })).rejects.toThrow("Nothing to update");
    expect(GET).not.toHaveBeenCalled();
    expect(POST).not.toHaveBeenCalled();
  });
});
